### ISSUE TITLE
¿Os funciona el del Himno de la Alegría?

### ISSUE THREAD

**Issue by Makova** [hack-miniblip/hack-miniblip.github.io#34]
A mi no, me tira el error en la línea 84:
`mySpeaker.PlaySong(note,duration);`

**Comment by Makova** [comment]
Este error:
`Error: Argument of type "float *" is incompatible with parameter of type "const std::uint8_t *" in "main.cpp", Line: 84, Col: 25`

**Comment by iblancasa** [comment]
Que raro... dame un rato y le echo un ojo.
Lo he hecho yo

**Comment by iblancasa** [comment]
¿Has añadido las dependencias? Fíjate que pone: You need SongPlayer.h created by https://developer.mbed.org/users/pighixxx/

Es decir, importas este: https://developer.mbed.org/users/pighixxx/code/blip_playnotes/ y pegas el main.cpp que hay aquí colgado en el del proyecto
