### ISSUE TITLE
¿De donde bajais las librerias?

### ISSUE THREAD

**Issue by Nitrosito** [hack-miniblip/hack-miniblip.github.io#42]
Pues eso, he llegado a casa y no he podido evitar probar algún codigo jaja. El caso es que he visto que usais librerias, y no se de donde sacarlas. He probado a bajarlas desde la herramienta de compilación (mbed creo que se la ha tragado) pero el neopixel o no logro elegir la correcta, o es que simplemente no está  en el repertorio

Las librerias son:
```#include "mbed.h"
# include "neopixel.h"```

**Comment by JJ** [comment]
Las librerías las incluye automáticamente. Compila y cuando no las encuentre haz "fixit". Lo pone en las instrucciones.

**Comment by Nitrosito** [comment]
Tienes razón @JJ  
Solucionado! ^^ Gracias!
