### ISSUE TITLE
Create web page

### ISSUE THREAD

**Issue by JJ** [hack-miniblip/hack-miniblip.github.io#59]
This repo is actually made for that kind of thing. Create HTML /Markdown page to link to all the stuff here

**Comment by iblancasa** [comment]
I think the best idea would be HTML with a template. Some sugerences:
- http://html5up.net/spectral (http://creativecommons.org/licenses/by/3.0/)
- http://html5up.net/landed  (http://creativecommons.org/licenses/by/3.0/) <- this is so Circolab

If I found something more...

**Comment by JJ** [comment]
Any one is cool.

**Comment by iblancasa** [comment]
I am going to work using landed (the second)

**Comment by angrykoala** [comment]
nw-miniblip in the end is node, just sayin'

**Comment by iblancasa** [comment]
@demiurgosoft yes but this is the editor. We are speaking about a web of the organisation.

I am working in it and in another thing. Soon

**Comment by iblancasa** [comment]
http://hack-miniblip.github.io/

**Comment by JJ** [comment]
Cool!

2015-12-02 13:18 GMT+01:00 Israel Blancas notifications@github.com:

> http://hack-miniblip.github.io/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hack-miniblip/hack-miniblip.github.io/issues/59#issuecomment-161275209
> .

## 

JJ

**Comment by victordiaz** [comment]
awesome!

**Comment by iblancasa** [comment]
@victordiaz Thanks :D
Can I close this issue?

**Comment by victordiaz** [comment]
@iblancasa I think so :) the web is great :)

**Comment by JJ** [comment]
Thanks!

2015-12-03 12:58 GMT+01:00 Victor Diaz notifications@github.com:

> @iblancasa https://github.com/iblancasa I think so :) the web is great
> :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hack-miniblip/hack-miniblip.github.io/issues/59#issuecomment-161610670
> .

## 

JJ

**Comment by iblancasa** [comment]
:D
