### ISSUE TITLE
Problemas con el loader MAC

### ISSUE THREAD

**Issue by mikiuma** [hack-miniblip/hack-miniblip.github.io#76]
He descargado el loader para Mac pero me lanza un error al descomprimirlo. Al final he conseguido descomprimirlo usando unzip desde el terminal pero, aun así, la aplicación no abre y lanza un error.

**Comment by iblancasa** [comment]
¿Podrías mostrarme un pantallazo del error? 
Nosotros no damos soporte directo a la aplicación, pero podemos intentar ayudarte :-)

**Comment by gvJaime** [comment]
A mí tambien me pasa, aquí tienes pantallazo:

![screen shot 2015-12-05 at 20 23 11](https://cloud.githubusercontent.com/assets/2140459/11609696/0864076c-9b8e-11e5-9ec7-14fe64c3affc.png)

Stuffit Xpander tampoco me lo descomprime. Dice que la estructura del archivo está dañada

**Comment by iblancasa** [comment]
Veréis yo no tengo un Mac. A ver cómo podemos solucionar el tema.

Os dejo un enlace a fichero original. En este fichero se encuentran los 3 loaders: Windows, Linux y Mac (yo lo separé y, probablemente, haya surgido algún problema). ¿Podríais comprobar si este funciona? Debería por que lo he visto funcionar.

[miniBLIP_loader.zip](https://github.com/hack-miniblip/hack-miniblip.github.io/files/52948/miniBLIP_loader.zip)

**Comment by gvJaime** [comment]
Sip! este sí que va.

**Comment by iblancasa** [comment]
Hazme un favor: comprime el de Mac, descomprímelo el otro directorio y comprueba que funciona.
Si funciona, súbemelo a este mismo hilo

**Comment by elgambitero** [comment]
No te lo vas a creer: incluso comprimiéndolo con el mac, no va. Creo que es alguna cosa de caracteres o algo. Voy a ver qué consigo.

**Comment by gvJaime** [comment]
[OSX_miniBLIP_loader.zip](https://github.com/hack-miniblip/hack-miniblip.github.io/files/52957/OSX_miniBLIP_loader.zip)

Ya lo conseguí. Aquí lo tenemos. 

Muchas gracias!!

**Comment by iblancasa** [comment]
Muchas gracias @elgambitero
